/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * ClienteFrame.java
 *
 * Created on 20/02/2011, 11:05:14
 */
package View;

import Controller.VendaDAO;
import Model.Cliente;
import Model.ItensVenda;
import Model.Produto;
import Model.Venda;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author Cleber
 */
public class FrmRegistraVenda extends javax.swing.JInternalFrame {

    private DefaultTableModel tableModel;
    private List<ItensVenda> itensVenda;
    private Produto produto;
    private Cliente cliente;

    /**
     * Creates new form ClienteFrame
     */
    public FrmRegistraVenda() {
        initComponents();
        //listar();
        defineModelo();
        itensVenda = new ArrayList<ItensVenda>();
    }

    private void defineModelo() {
        tableModel = (DefaultTableModel) jTblItensVenda.getModel();
        try {
            DecimalFormat formatoValor = new DecimalFormat("#,###.00");
            NumberFormatter formatterValor = new NumberFormatter(formatoValor);
            formatterValor.setValueClass(Double.class);
            jTxtValorTotal.setFormatterFactory(new DefaultFormatterFactory(formatterValor));

            DecimalFormat formatoEstoque = new DecimalFormat("#,###");
            NumberFormatter formatterEstoque = new NumberFormatter(formatoEstoque);
            formatterEstoque.setValueClass(Integer.class);
            jTxtQuantidade.setFormatterFactory(new DefaultFormatterFactory(formatterEstoque));

            jTblItensVenda.getColumnModel().getColumn(0).setPreferredWidth(400);
        } catch (Exception ex) {
            Logger.getLogger(FrmRegistraVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void listar() {
       
        int numeroLinhas = jTblItensVenda.getRowCount();
        for (int i = 0; i < numeroLinhas; i++) {
            tableModel.removeRow(0);
        }
        double valorTotal = 0.0;
        
        for (int i = 0; i < itensVenda.size(); i++) {
            tableModel.insertRow(i, new Object[]{itensVenda.get(i).getProduto().getNome(),
                itensVenda.get(i).getQtde(),
                itensVenda.get(i).getProduto().getValor(),
                itensVenda.get(i).getProduto().getValor() * itensVenda.get(i).getQtde()
            });
            valorTotal += itensVenda.get(i).getProduto().getValor() * itensVenda.get(i).getQtde();
        }
        jTxtValorTotal.setValue(valorTotal);

    }

    private void incluirProduto() {
        if (produto == null) {
            JOptionPane.showMessageDialog(this, "Selecionar o produto!", "Erro", JOptionPane.ERROR_MESSAGE);
            jBtnSelecionaProduto.requestFocus();
        } else if (jTxtQuantidade.getText() == null) {
            JOptionPane.showMessageDialog(this, "Informe a quantidade!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            ItensVenda item = new ItensVenda();
            item.setProduto(produto);
            item.setQtde((Integer) jTxtQuantidade.getValue());
            item.setValor(produto.getValor());

            itensVenda.add(item);
            listar();
        }
    }

    private void excluirProduto() {
        if (jTblItensVenda.getSelectedRow() != -1) {
            itensVenda.remove(jTblItensVenda.getSelectedRow());
            listar();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um item da lista!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void registarVenda() {
        if (getCliente() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else if (itensVenda.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Insira itens na venda!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            Venda venda = new Venda();
            venda.setCliente(getCliente());

            Calendar dataAtual = Calendar.getInstance();
            venda.setDataVenda(new java.sql.Date(dataAtual.getTime().getTime()));

            venda.setItensVenda(itensVenda);

            VendaDAO vendaDAO = new VendaDAO();
            if (vendaDAO.registrarVenda(venda)) {
                JOptionPane.showMessageDialog(this, "Venda registrada com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTxtValorTotal = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNomeCliente = new javax.swing.JTextField();
        jBtnSelecionaCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblItensVenda = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTxtNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtQuantidade = new javax.swing.JFormattedTextField();
        jBtnSelecionaProduto = new javax.swing.JButton();
        jBtnIncluiProduto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBtnExcluiItem = new javax.swing.JButton();
        jBtnRegistraVenda = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Java GUI Swing - TADS 2023 - IFMT/ROO");
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Venda");
        jPanel1.add(jLabel1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel6.setText("Valor Total");
        jPanel2.add(jLabel6);

        jTxtValorTotal.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel2.add(jTxtValorTotal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel2, gridBagConstraints);

        jTxtNomeCliente.setEditable(false);
        jTxtNomeCliente.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jTxtNomeCliente, gridBagConstraints);

        jBtnSelecionaCliente.setText("...");
        jBtnSelecionaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelecionaClienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jBtnSelecionaCliente, gridBagConstraints);

        jTblItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Qtde", "Vlr. Unit.", "Vlr. Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTblItensVenda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTblItensVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jScrollPane1, gridBagConstraints);

        jLabel7.setText("Produto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel7, gridBagConstraints);

        jTxtNomeProduto.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jTxtNomeProduto, gridBagConstraints);

        jLabel3.setText("Qtde");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jTxtQuantidade, gridBagConstraints);

        jBtnSelecionaProduto.setText("...");
        jBtnSelecionaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSelecionaProdutoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jBtnSelecionaProduto, gridBagConstraints);

        jBtnIncluiProduto.setText("Incluir");
        jBtnIncluiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluiProdutoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel3.add(jBtnIncluiProduto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnExcluiItem.setText("Excluir Item");
        jBtnExcluiItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluiItemActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnExcluiItem);

        jBtnRegistraVenda.setText("Salvar");
        jBtnRegistraVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistraVendaActionPerformed(evt);
            }
        });
        jPanel4.add(jBtnRegistraVenda);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSelecionaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecionaClienteActionPerformed
        FrmCliente clienteFrame = new FrmCliente(this);
        clienteFrame.setVisible(true);
        this.getDesktopPane().add(clienteFrame);
        clienteFrame.toFront();
    }//GEN-LAST:event_jBtnSelecionaClienteActionPerformed

    private void jBtnExcluiItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluiItemActionPerformed
        excluirProduto();
    }//GEN-LAST:event_jBtnExcluiItemActionPerformed

    private void jBtnRegistraVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistraVendaActionPerformed
        registarVenda();
    }//GEN-LAST:event_jBtnRegistraVendaActionPerformed

    private void jBtnIncluiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluiProdutoActionPerformed
        incluirProduto();
    }//GEN-LAST:event_jBtnIncluiProdutoActionPerformed

    private void jBtnSelecionaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSelecionaProdutoActionPerformed
        FrmProduto produtoFrame = new FrmProduto(this);
        produtoFrame.setVisible(true);
        this.getDesktopPane().add(produtoFrame);
        produtoFrame.toFront();
    }//GEN-LAST:event_jBtnSelecionaProdutoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExcluiItem;
    private javax.swing.JButton jBtnIncluiProduto;
    private javax.swing.JButton jBtnRegistraVenda;
    private javax.swing.JButton jBtnSelecionaCliente;
    private javax.swing.JButton jBtnSelecionaProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblItensVenda;
    private javax.swing.JTextField jTxtNomeCliente;
    private javax.swing.JTextField jTxtNomeProduto;
    private javax.swing.JFormattedTextField jTxtQuantidade;
    private javax.swing.JFormattedTextField jTxtValorTotal;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the produto
     */
    public Produto getProduto() {
        return produto;
    }

    /**
     * @param produto the produto to set
     */
    public void setProduto(Produto produto) {
        this.produto = produto;
        jTxtNomeProduto.setText(produto.getNome());
    }

    /**
     * @return the cliente
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * @param cliente the cliente to set
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
        jTxtNomeCliente.setText(cliente.getNome());
    }
}
